Repository boltops-tools/jets, pull requests merged in 2021-01, with the labels that each got.

#457 Improve iam_policy configuration
  lib/jets/application.rb
  lib/jets/application/defaults.rb
  spec/lib/jets/application_spec.rb
  spec/lib/jets/resource/iam/class_role_spec.rb
  spec/lib/jets/resource/iam/function_role_spec.rb
Labels: pending issuer

#488 Add retry_limit and read_timeout options
  lib/jets/commands/call.rb
  lib/jets/commands/help/call.md
  lib/jets/commands/main.rb
  spec/lib/jets/commands/call_spec.rb
Labels: pending qa

#491 Fix queryStringParameters handling for nested value in spec_helper
  lib/jets/spec_helpers/controllers/request.rb
  spec/lib/jets/spec_helpers_spec.rb
Labels: pending review

#496 Add unicode test for spec_helpers test
  lib/jets/router/dsl.rb
  lib/jets/spec_helpers/controllers/request.rb
  spec/lib/jets/spec_helpers_spec.rb
Labels: pending qa
